name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Test changes from PRs
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    if: github.ref != 'refs/heads/master'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run:  |
              npm -v
              npm ci
              npm list @qooxdoo/framework
              npm test
        env:
          CI: true
          
      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          NGROK_TOKEN: 1mgQP3LIPJVeX1aMfNXNmfOUEWd_7y7D4XXQmtNRTMr8yBtef
          USER_PASS: qbX3oLMk8j
         
      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h # Prevent to killing instance after failure

  deploy:
    name: Deploy API Viewer
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install
        run:  |
              npm ci
              ./bootstrap-compiler
      - name: Build API Viewer
        run:  npx qx deploy app-name="apiviewer" 
      - name: Deploy API Viewer
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
      - name: dispatch to deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          repository: qooxdoo/deployment
          event-type: deploy
